import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import NextTopLoader from "nextjs-toploader";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { redirect } from "next/navigation";
import { getUser } from "@/lib/actions/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayoutAuth({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <NextTopLoader showSpinner={false} />
        <ThemeProvider
          defaultTheme="light"
          attribute="class"
          disableTransitionOnChange
        >
          <p>dashboard group pages</p>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
